version: 2.1
jobs:
  # go project build
  build:
    docker:
      - image: golang:1.12-stretch
    steps:
      - checkout
      - run: make
      - store_artifacts:
          path: app
          destination: app

workflows:
  version: 2
  build-and-package:
    jobs:
      - build
