version: 2.1
jobs:
  # go project build
  build:
    docker:
      - image: golang:1.12-stretch
    steps:
      - checkout
      - run: make
      - store_artifacts:
          path: app
          destination: app

  # deploy to aws
  deploy:
    docker:
      - image: python:3-stretch
    steps:
      - checkout
      - run: pip install awscli --upgrade
      - run: apt-get update && apt-get install -y zip
      - run: make build deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
